name: CDK autogen sanity check
on:
  pull_request:
jobs:
  cdk-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      - name: Create temporary directory
        run: mkdir -p bigid/solutions/CloudNativeScanner-cdk
      - name: Change directory to temporary directory
        run: cd bigid/solutions/CloudNativeScanner-cdk && cdk migrate --language typescript --from-path ../CloudNativeScanner/scanner.yaml --stack-name bigid-scanner