name: CDK autogen sanity check

on:
  pull_request:
    branches:
      - '*'

jobs:
  cdk-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Install Rain
        run: go install github.com/aws-cloudformation/rain/cmd/rain@latest
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      - name: Create temporary directory
        run: mkdir -p bigid/solutions/CloudNativeScanner-cdk
      - name: Change directory to temporary directory
        run: cd bigid/solutions/CloudNativeScanner-cdk && rain fmt ../CloudNativeScanner/scanner.yaml -j > ../CloudNativeScanner/scanner.json  && cdk migrate --language typescript --from-path ../CloudNativeScanner/scanner.json --stack-name bigid-scanner
