name: scanner validation

on:
  pull_request:
    branches:
      - '*'

env:
  TEMPLATE_PATH: ./bigid/solutions/CloudNativeScanner/scanner.yaml

jobs:
  validate-cfn:
    name: Validate CloudFormation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        pip install cfn-lint

    - name: Print the Cloud Formation Linter Version & run Linter.
      run: |
        cfn-lint --version
        cfn-lint -t ${TEMPLATE_PATH} -I
