name: Lambda

on:
  push:
    branches: [ "master" ]
    paths:
      - 'bigid/solutions/CloudNativeScanner/ecs-scaler-lambda/ecs_scaler_lambda.py'
  workflow_dispatch:

jobs:
  deploy:
    name: Build Lambda and Push To S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0" # Replace with your required version
      - name: Install dependencies
        run: |
          cd bigid/solutions/CloudNativeScanner/ecs-scaler-lambda/
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target ./package
      - name: Prepare package
        run: |
          cd bigid/solutions/CloudNativeScanner/ecs-scaler-lambda/
          mkdir -p package
          cp -R $(ls | grep -v 'package') package/
          cd package
          zip -r ../ecs-scaler-lambda.zip .
          echo $PWD
          ls -alh ../   
      - name: Configure AWS credentials from Prod account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::835626702473:role/github-actions-aws-cloud-formation-templates-role
          aws-region: us-east-1
      - name: Upload Lambda function to S3
        run: |
          cd bigid/solutions/CloudNativeScanner/ecs-scaler-lambda/
          aws s3 cp ecs-scaler-lambda.zip s3://bigid-cloudformation-templates/ecs-scaler-lambda.zip
