# AWS Cloudformation Templates Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'bigid/solutions/CloudNativeScanner/ecs-scaler-lambda/'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Scanner.yaml Copy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Prod account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::835626702473:role/github-actions-aws-cloud-formation-templates-role
        aws-region: us-east-1
    - name: Copy scanner.yaml to the production bucket.
      run: |
        aws s3 cp bigid/solutions/CloudNativeScanner/scanner.yaml s3://bigid-cloudformation-templates  --acl public-read
