name: AWS Cloudformation Templates Actions

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  s3-upload:
    name: Scanner.yaml Copy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
<<<<<<< HEAD
=======

>>>>>>> 667d7e6 (Update upload.yml)
      - name: Configure AWS credentials from Prod account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::835626702473:role/github-actions-aws-cloud-formation-templates-role
          aws-region: us-east-1
<<<<<<< HEAD
      - name: Copy scanner.yaml to the production bucket
        run: aws s3 cp bigid/solutions/CloudNativeScanner/scanner.yaml s3://bigid-cloudformation-templates --acl public-read
=======
        
      - name: Copy scanner.yaml to the appropriate path in the bucket
        run: |
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
          aws s3 cp bigid/solutions/CloudNativeScanner/scanner.yaml s3://bigid-cloudformation-templates/bigid/solutions/CloudNativeScanner/scanner.yaml --acl public-read
          aws s3 cp bigid/solutions/CloudNativeScanner/scanner.yaml s3://bigid-cloudformation-templates/bigid/solutions/CloudNativeScanner/scanner-${{ github.ref_name }}.yaml --acl public-read
>>>>>>> 667d7e6 (Update upload.yml)
=======
          aws s3 cp bigid/solutions/CloudNativeScanner/scanner.yaml s3://bigid-cloudformation-templates/scanner.yaml --acl public-read
=======
>>>>>>> d23a73d (BCO-0000)
=======
>>>>>>> e6034c2 (BCO-0000)
          aws s3 cp bigid/solutions/CloudNativeScanner/scanner.yaml s3://bigid-cloudformation-templates/scanner-${{ github.ref_name }}.yaml --acl public-read
>>>>>>> 8677631 (Update upload.yml)

  lambda-upload:
    needs: s3-upload
    name: Build Lambda and Push To S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
<<<<<<< HEAD
=======

>>>>>>> 667d7e6 (Update upload.yml)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - name: Install dependencies
        run: |
          cd $S3_PREFIX/ecs-scaler-lambda/
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target ./package
      - name: Prepare package
        run: |
          cd $S3_PREFIX/ecs-scaler-lambda/
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          deactivate
          mkdir -p package
          cp -R venv/lib/python3.11/site-packages/* package/
          cp ecs_scaler_lambda.py package/
          cd package
          zip -r ../ecs-scaler-lambda.zip .
      - name: Configure AWS credentials from Prod account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::835626702473:role/github-actions-aws-cloud-formation-templates-role
          aws-region: us-east-1
      - name: Get Version and Upload Lambda function to S3
        run: |
          # Extract version
          LAMBDA_VERSION=$(yq -r '.Resources.ECSScalerLambdaVersion.Properties.Description' ./bigid/solutions/CloudNativeScanner/scanner.yaml)
          echo "Lambda version: $LAMBDA_VERSION"

          # Navigate to the correct directory
<<<<<<< HEAD
          cd bigid/solutions/CloudNativeScanner/ecs-scaler-lambda/

          # Upload to S3
          aws s3 cp ecs-scaler-lambda.zip s3://bigid-ecs-lambda-scaler-us-east-1/ecs-scaler-lambda-$LAMBDA_VERSION.zip --acl public-read
=======
          cd $S3_PREFIX/ecs-scaler-lambda/
          
          # Upload to S3
          aws s3 cp ecs-scaler-lambda.zip s3://bigid-ecs-lambda-scaler-us-east-1/ecs-scaler-lambda-$LAMBDA_VERSION.zip --acl public-read
<<<<<<< HEAD
          aws s3 cp ecs-scaler-lambda.zip s3://bigid-ecs-lambda-scaler-us-east-1/ecs-scaler-lambda-$LAMBDA_VERSION-${{ github.ref_name }}.zip --acl public-read
          
          
  
>>>>>>> 667d7e6 (Update upload.yml)
=======
          aws s3 cp ecs-scaler-lambda.zip s3://bigid-ecs-lambda-scaler-us-east-1/ecs-scaler-lambda-${{ github.ref_name }}.zip --acl public-read
>>>>>>> 8677631 (Update upload.yml)
